# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"(\n\x07Message\x12\x0c\n\x04role\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"\xa6\x01\n\x0b\x43hatRequest\x12\x1f\n\x08messages\x18\x01 \x03(\x0b\x32\r.chat.Message\x12\x12\n\nsession_id\x18\x02 \x01(\t\x12\x31\n\x08metadata\x18\x03 \x03(\x0b\x32\x1f.chat.ChatRequest.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"O\n\x05Usage\x12\x15\n\rprompt_tokens\x18\x01 \x01(\x05\x12\x19\n\x11\x63ompletion_tokens\x18\x02 \x01(\x05\x12\x14\n\x0ctotal_tokens\x18\x03 \x01(\x05\"d\n\x0c\x43hatResponse\x12\r\n\x05reply\x18\x01 \x01(\t\x12\x1a\n\x05usage\x18\x02 \x01(\x0b\x32\x0b.chat.Usage\x12\x12\n\nerror_code\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t2>\n\rOpenAIService\x12-\n\x04\x43hat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse2<\n\x0bQwenService\x12-\n\x04\x43hat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse2>\n\rDoubaoService\x12-\n\x04\x43hat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponse2>\n\rMinMaxService\x12-\n\x04\x43hat\x12\x11.chat.ChatRequest\x1a\x12.chat.ChatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST_METADATAENTRY']._loaded_options = None
  _globals['_CHATREQUEST_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_MESSAGE']._serialized_start=20
  _globals['_MESSAGE']._serialized_end=60
  _globals['_CHATREQUEST']._serialized_start=63
  _globals['_CHATREQUEST']._serialized_end=229
  _globals['_CHATREQUEST_METADATAENTRY']._serialized_start=182
  _globals['_CHATREQUEST_METADATAENTRY']._serialized_end=229
  _globals['_USAGE']._serialized_start=231
  _globals['_USAGE']._serialized_end=310
  _globals['_CHATRESPONSE']._serialized_start=312
  _globals['_CHATRESPONSE']._serialized_end=412
  _globals['_OPENAISERVICE']._serialized_start=414
  _globals['_OPENAISERVICE']._serialized_end=476
  _globals['_QWENSERVICE']._serialized_start=478
  _globals['_QWENSERVICE']._serialized_end=538
  _globals['_DOUBAOSERVICE']._serialized_start=540
  _globals['_DOUBAOSERVICE']._serialized_end=602
  _globals['_MINMAXSERVICE']._serialized_start=604
  _globals['_MINMAXSERVICE']._serialized_end=666
# @@protoc_insertion_point(module_scope)
